[phases.setup]
nixPkgs = ["php84", "php84Extensions.pdo_mysql", "php84Extensions.mbstring", "php84Extensions.exif", "php84Extensions.bcmath", "php84Extensions.gd", "composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = ["php artisan optimize:clear", "php artisan storage:link"]

[phases.migrate]
cmds = ["php artisan migrate --force"]

[phases.start]
cmds = ["php artisan serve --host=0.0.0.0 --port=$PORT"]